# fly.toml app configuration file generated for basecamp-2 on 2023-09-19T12:46:12+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "basecamp-2"
primary_region = "dfw"
console_command = "/rails/bin/rails console"

[build]

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
